---
- name: "Install webapp"
  become: yes
  hosts: prod
  vars_files:
   - files/secrets/credentials.yml
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: "clean folder"
      file:
        path: /home/{{ ansible_user }}/webapp
        state: absent
    - name: create webapp directory
      file :
        path: /home/{{ ansible_user }}/webapp/
        state: directory
#    - name: "install git"
#      yum:
#        name: git
#        state: present
#        update_cache: yes
#    - name: "git clone to nginx folder"
#      git:
#        repo: https://github.com/diranetafen/static-website-example.git
#        dest: /home/{{ ansible_user }}/webapp/
    - name: Generate html
      template:
        src: templates/index.html.j2
        dest: /home/{{ ansible_user }}/webapp/index.html
    - name: "Lauching an HTTPD Container"
      docker_container:
        name: nginx-server
        image: nginx
        state: started
        ports:
          - "8080:80"
        volumes:
          - /home/{{ ansible_user }}/webapp:/usr/share/nginx/html
